language: bash

sudo: required

service:
- docker

before_install:
- docker build -t todo-app-test:latest .

script:
- docker run -e TRELLO_API_SECRET -e TRELLO_API_KEY -e SECRET_KEY -e TRELLO_BOARD_NAME --entrypoint poetry todo-app-test:latest run pytest tests
- docker run -e TRELLO_API_SECRET -e TRELLO_API_KEY -e SECRET_KEY --entrypoint poetry todo-app-test:latest run pytest tests_e2e

after_success:
- echo "All done!"

notifications:
  email:
    on_success: never
    on_failure: always
  slack: corndeldevops-jul3809:75aSeUKEXlO7OZDFCTNoke3J

