language: bash

sudo: required

service:
- docker

before_install:
#- env > .env
- docker build -t todo-app-test:latest .
- docker run --entrypoint "tail -f /dev/null" -d todo-app-test:latest

script:
#- docker run --entrypoint "poetry run pytest tests" todo-app-test:latest
#- docker run -e TRELLO_API_SECRET -e TRELLO_API_KEY todo-app-test:latest
#- docker run --name TODO-APP -dp 5000:5000 todo-app-test:latest
- docker exec -t -i TODO-APP sh -c "poetry run pytest tests"
#- docker exec -t -i TODO-APP sh -c "poetry run pytest tests_e2e"

after_success:
- echo "All done!"

notifications:
  email:
    on_success: never
    on_failure: always
  slack: corndeldevops-jul3809:75aSeUKEXlO7OZDFCTNoke3J

