language: bash
sudo: required
service:
- docker
before_install:
- docker build -t todo-app-test:latest .
script:
- docker run -e TRELLO_API_SECRET -e TRELLO_API_KEY -e SECRET_KEY --entrypoint poetry
  todo-app-test:latest run pytest
after_success:
- echo "All done!"
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: "S6QJACOS0K7aKLtkvcMNUuTkEoPDxhiX9SRQXS8FcT+B39ynUthC2QR5lR+Y0GNEDDT7+GtJEEzB+mF/EMtoRds198NU4Rzg2E8XoX/LEFCvpCjQWUXo6GozxhCEuh6mIdGrxcpSlgcUBp7tZXw2H+iT+Nf9ZK2xTX7Pb8pyHc1q5a0cMRCyJskxhZphbLVh3Glj/S8fT5fcZn0RnGhL3aSZvpiSRguTTnAafERUuBrVIn4g0+D97hknqcIj3G4XBbmoYFT6bdO1y/p0YEcfcDZFRvpC7Ldu9OjZLfPgLq+TRAh7r9nRdU2KW4bBuwcRCIYGN4Q0HiCZF9i/uSfSMTMcfgsXYlXNNjT0bg8Xfpvp2dacvplqvgSnLZCma4659Gw9WKtrGaenVDoq8t3HoogLWMookXwgJOPPqu7nELBQKmp492xw0N1dGCS4YKW71kHnS/G3ftIsThM6f0M2EwP1+99Q/Vr2gL/9ggd87FMuoRjWhEz5oi/ggQUYTM5BLhQHcXWtMHaCbcCUVdX+Bw6z+42EK2AuOWCl+tZZbIXg5nOrth1yL+Tq2na1ODt2adkDhoLbocsVrlkDJnxTMpdJAEvT+XSUozkSuxAbi/Pv9j907Vu2jPvO7Rgt80xbwXkhWH823Npmo1h1SJsv6xyLVdgX0dawIYZCBKNiTgg="
