version: "3.7" 

services:
  prodapp:
    container_name: todo-app-prod
    env_file:
      - .env
    build:      
      context: .
      dockerfile: Dockerfile
      target: production
    image: todo-app:prod
    ports:
      - 5000:5000