version: "3.3" 

services:
  devapp:
    container_name: todo-app-dev
    build:      
      context: .
      dockerfile: Dockerfile
      target: development
    image: todo-app-dev:latest
    volumes: 
      - type: bind
        source: .
        target: /app
    ports:
      - 5000:5000

  
  testapp:
    container_name: todo-app-test
    build:      
      context: .
      dockerfile: Dockerfile
      target: test
    image: todo-app-test:latest
    volumes: 
      - type: bind
        source: .
        target: /app    